### PR TITLE
Use luajit2 on s390x

### PR DESCRIPTION
**Pull request by knm3000**

### CODE REVIEW

**Comment by jwendell** [comment]
I guess we depend on https://github.com/maistra/envoy/pull/130 for this to work, right?
Also, unfortunately our CI tests on prow only run for x86-64, JFYI.

**Comment by knm3000** [comment]
Correct, [maistra/envoy#130](https://github.com/maistra/envoy/pull/130) is a prerequisite.

**Comment by yselkowitz** [comment]
Do we want to do this in 2.1.z or wait until 2.2?  Or IOW, is a luajit rebase planned for 2.1.z?

**Comment by yselkowitz** [comment]
For 2.1.0 this is building on s390x with patched luajit.  The switch to luajit2 is only needed upon a rebase of luajit (on which the s390x patch does not apply).  So unless you plan on rebasing luajit in 2.1.z, or there is a bug in the http.lua filter with 2.1 on s390x, waiting to switch until 2.2 seems to be prudent.
/hold

**Comment by knm3000** [comment]
Opened another PR https://github.com/maistra/proxy/pull/154 against maistra-2.2 instead of this one.

**Pull request closed without merging**
