### PR TITLE
Disable s390x LuaJIT builds in envoy

### PR DESCRIPTION
**Pull request by knrc**
Temporarily disable s390x builds of LuaJIT.  Note PPC already appears to be disabled.

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
Why not just put `ExclusiveArch: x86` in .spec until MAISTRA-2379 is resolved?

**Comment by knrc** [comment]
> Why not just put `ExclusiveArch: x86` in .spec until MAISTRA-2379 is resolved?

Because that means it only builds for x86 and not for the other two, this way it builds for all three but just skips the LuaJIT inclusion,=.  Everything needs to be multi arch now, x86 only is not an option

**Review by brian-avery — APPROVED** [review]

**Comment by jwendell** [comment]
> > Why not just put `ExclusiveArch: x86` in .spec until MAISTRA-2379 is resolved?
> 
> Because that means it only builds for x86 and not for the other two, this way it builds for all three but just skips the LuaJIT inclusion,=. Everything needs to be multi arch now, x86 only is not an option

This is a temporary thing. Hence my suggestion.

**Comment by knrc** [comment]
> This is a temporary thing. Hence my suggestion.

We need to keep building for the Z/P architectures, temporary or otherwise.  This approach disables only the LuaJIT integration and allows the Z/P QE teams to move forward with 2.1 efforts in the meantime.

In addition, I discovered when looking into this is that we are already disabling LuaJIT for PPC and that is something else which needs addressing.  Note the scratch build I ran yesterday succeeded for all architectures.

**Comment by jwendell** [comment]
> > This is a temporary thing. Hence my suggestion.
> 
> We need to keep building for the Z/P architectures, temporary or otherwise. This approach disables only the LuaJIT integration and allows the Z/P QE teams to move forward with 2.1 efforts in the meantime.

OK, SGTM then. Can this patch be moved to Envoy directly then? I mean, no need to patch, just submit a proper PR in maistra/envoy. It will be picked up automatically by proxy after merging.

> In addition, I discovered when looking into this is that we are already disabling LuaJIT for PPC and that is something else which needs addressing. Note the scratch build I ran yesterday succeeded for all architectures.

Cool. Create a ticket for it then.

**Comment by knrc** [comment]
> OK, SGTM then. Can this patch be moved to Envoy directly then? I mean, no need to patch, just submit a proper PR in maistra/envoy. It will be picked up automatically by proxy after merging.

 I thought about that but the patch in the proxy source seemed easier for now, less likely to get lost and easier to spot when we reenable it

> > In addition, I discovered when looking into this is that we are already disabling LuaJIT for PPC and that is something else which needs addressing. Note the scratch build I ran yesterday succeeded for all architectures.
> 
> Cool. Create a ticket for it then.

I did yesterday :)

**Pull request merged**
