### PR TITLE
CI: Tidy build output

### PR DESCRIPTION
**Pull request by jwendell**
By removing extra, unnecessary output that makes it
difficult to inspect the build log.

### CODE REVIEW

**Comment by jwendell** [comment]
Before:
```
$ curl https://storage.googleapis.com/maistra-prow-testing/pr-logs/pull/maistra_proxy/68/proxy_2.0-unit/1333415764811583488/build-log.txt | wc -l
153071
```

After:
```
$ curl https://storage.googleapis.com/maistra-prow-testing/pr-logs/pull/maistra_proxy/69/proxy_2.0-unit/1333471381630750720/build-log.txt | wc -l
2999
```

**Comment by dgn** [comment]
> Before:
> 
> ```
> $ curl https://storage.googleapis.com/maistra-prow-testing/pr-logs/pull/maistra_proxy/68/proxy_2.0-unit/1333415764811583488/build-log.txt | wc -l
> 153071
> ```
> 
> After:
> 
> ```
> $ curl https://storage.googleapis.com/maistra-prow-testing/pr-logs/pull/maistra_proxy/69/proxy_2.0-unit/1333471381630750720/build-log.txt | wc -l
> 2999
> ```

~That comparison isn't really fair as this PR's build happened with a warm cache and no code changes~ that's wrong, see below

**Review by dgn — APPROVED** [review]
lgtm. adding hold so @dmitri-d has a chance to review

/hold

**Comment by jwendell** [comment]
@dgn This has nothing to do with build time, but with the size of the build log. This PR removes clutter from logs that happen regardless of cache usage.

**Comment by dgn** [comment]
> @dgn This has nothing to do with build time, but with the size of the build log. This PR removes clutter from logs that happen regardless of cache usage.

+1 but with a warm cache you won't get a lot of those log lines afaict

**Comment by dgn** [comment]
Nevermind you're right, still 153k lines on a warm cache

**Comment by dmitri-d** [comment]
The amount of stuff being logged can be reduced (definitely the items in `OUTPUT_TO_IGNORE`) by removing `sandbox_debug` option, here: https://github.com/maistra/proxy/blob/maistra-2.0/maistra/bazelrc#L22. Should we try getting rid of that first?

**Comment by jwendell** [comment]
@dmitri-d  Even without that flag I still see clutter in the logs. I'll open another PR so that we can see it in practice and compare.

**Review by dmitri-d — APPROVED** [review]

**Pull request merged**
