### PR TITLE
[OSSM-107] Move luajit patches to envoy

### PR DESCRIPTION
**Pull request by yselkowitz**
**What this PR does / why we need it**:

This re-enables lua extension support for P&Z, by fixing the luajit
s390x patch, and using moonjit for ppc64le.

﻿- Rebase luajit s390x patch
- Re-enable application of luajit s390x patch
- Apply luajit s390x patch to vendored copy
- Enable s390x LuaJIT builds in envoy
- Enable ppc64le LuaJIT builds in envoy

**Special notes for your reviewer**:

This requires a spec file change to build with moonjit on ppc64le only.

### CODE REVIEW

**Comment by dmitri-d** [comment]
Thanks for the PR! Could you open the PR against maistra-envoy (https://github.com/maistra/envoy) instead?

* Instead of applying patches in `maistra/scripts/update-deps.sh`, you'd need to update `patches` list here: https://github.com/envoyproxy/envoy/blob/main/bazel/repositories.bzl#L892.
* Could you include `dynasm/dasm_s390x.h` and other additions in the patch too? We can't rely on modifications to vendored files, as these are automatically fetched and updated.
* Ditto changes in existing files (FWIW you could use git format-patch on the commits you made to upstream lua-jit, and then use this/these patches in bazel/repositories.bzl). 
* Changes to `bazel/repositories.bzl`, `source/exe/BUILD` and other files in Envoy source tree are ok and can be made directly.

 @jwendell: could you take a look please?

**Comment by jwendell** [comment]
Agreed with Dmitri. The right link to repositories.bzl is https://github.com/maistra/envoy/blob/maistra-2.1/bazel/repositories.bzl#L846 (maistra/envoy fork instead of upstream envoy/envoy)

Just to be clear: Changes made in maistra/envoy are automatically picked up by this repo, via update-deps.sh script.

**Comment by yselkowitz** [comment]
Just reworked this PR to remove all luajit patches from proxy; this is co-dependent with https://github.com/maistra/envoy/pull/103.

**Review by jwendell — CHANGES_REQUESTED** [review]
I think you will want to update this PR to contain all the stuff that's coming from Envoy when https://github.com/maistra/envoy/pull/103 merges.

Once it merges, an automated PR will be created on this repo, containing the output of `make maistra-update-everything`. You can run this command yourself and commit the changes, along with the ones in this PR. And we can close the automated PR and merge yours.

**Comment by yselkowitz** [comment]
It seems doing that would require a specifically configured development environment, which I do not have at the moment.  IIUC the workflow, it would seem this would need to be merged just before the envoy PR, and then the automation should do the right thing.  Does that make sense?

**Comment by jwendell** [comment]
automation failed. You need to do this manually. We have a container for that. Ask me details in Slack. Or I can take this over too.

**Comment by dmitri-d** [comment]
@yselkowitz: any reason the patches here cannot be moved to maistra-envoy too?

**Comment by jwendell** [comment]
> @yselkowitz: any reason the patches here cannot be moved to maistra-envoy too?

They were

**Review by jwendell — APPROVED** [review]

**Pull request merged**
